/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as PublicInitialSetupRouteImport } from './routes/_public/initial-setup'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminReviewsIndexRouteImport } from './routes/_admin/reviews/index'
import { Route as AdminMosquesIndexRouteImport } from './routes/_admin/mosques/index'
import { Route as AdminEventsIndexRouteImport } from './routes/_admin/events/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInitialSetupRoute = PublicInitialSetupRouteImport.update({
  id: '/initial-setup',
  path: '/initial-setup',
  getParentRoute: () => PublicRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMosquesIndexRoute = AdminMosquesIndexRouteImport.update({
  id: '/mosques/',
  path: '/mosques/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/initial-setup': typeof PublicInitialSetupRoute
  '/sign-in': typeof PublicSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/events/': typeof AdminEventsIndexRoute
  '/mosques/': typeof AdminMosquesIndexRoute
  '/reviews/': typeof AdminReviewsIndexRoute
  '/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/initial-setup': typeof PublicInitialSetupRoute
  '/sign-in': typeof PublicSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/events': typeof AdminEventsIndexRoute
  '/mosques': typeof AdminMosquesIndexRoute
  '/reviews': typeof AdminReviewsIndexRoute
  '/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_public/initial-setup': typeof PublicInitialSetupRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_admin/events/': typeof AdminEventsIndexRoute
  '/_admin/mosques/': typeof AdminMosquesIndexRoute
  '/_admin/reviews/': typeof AdminReviewsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/initial-setup'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/events/'
    | '/mosques/'
    | '/reviews/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/initial-setup'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/events'
    | '/mosques'
    | '/reviews'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_public'
    | '/_admin/dashboard'
    | '/_public/initial-setup'
    | '/_public/sign-in'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_admin/events/'
    | '/_admin/mosques/'
    | '/_admin/reviews/'
    | '/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/initial-setup': {
      id: '/_public/initial-setup'
      path: '/initial-setup'
      fullPath: '/initial-setup'
      preLoaderRoute: typeof PublicInitialSetupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reviews/': {
      id: '/_admin/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/mosques/': {
      id: '/_admin/mosques/'
      path: '/mosques'
      fullPath: '/mosques/'
      preLoaderRoute: typeof AdminMosquesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events/': {
      id: '/_admin/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminMosquesIndexRoute: typeof AdminMosquesIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminMosquesIndexRoute: AdminMosquesIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicInitialSetupRoute: typeof PublicInitialSetupRoute
  PublicSignInRoute: typeof PublicSignInRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicInitialSetupRoute: PublicInitialSetupRoute,
  PublicSignInRoute: PublicSignInRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
